# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: assistant_architect

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ru

pipeline:
  - name: "SpacyNLP"
    model: "ru_core_news_sm"
    case_sensitive: False
  - name: "SpacyTokenizer"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  # Подключение предобученной модели трансформера (BERT)
  - name: "LanguageModelFeaturizer"
    model_name: "bert"                      # Модель BERT для русского языка
    model_weights: "bert-base-cased"        # Весы модели BERT
    cache_dir: null

  - name: DIETClassifier                    # Классификатор на базе DIET
    epochs: 100                              # Минимальное количество эпох обучения
    transformer_size: 256                    # Минимальный размер слоя трансформера
    number_of_transformer_layers: 2       # Один слой трансформера
    use_masked_language_model: true        # Отключено для ускорения
    batch_strategy: "balanced"
    hidden_layers_sizes:
      text: [256, 128]

  - name: EntitySynonymMapper
  - name: ResponseSelector                      # Модель для выбора ответа
    epochs: 100
#  - name: FallbackClassifier
#    threshold: 0.7

policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
